(define (problem toh-test-05)
	(:domain toh-domain)
  	(:objects a b c lpeg mpeg rpeg)
   	(:init 
	   (disk a) (disk b) (disk c) (peg lpeg) (peg mpeg) (peg rpeg)
	   (at a lpeg) (at b lpeg) (at c lpeg)
	   (on a b) (on b c)
	   (at-bottom c lpeg)
	   (clear a)
	   (smaller a b)
	   (smaller b c)
	   (empty mpeg)
	   (empty rpeg))
	(:goal (and (at a rpeg) (at b rpeg) (at c rpeg)
	            (on a b) (on b c))))
