;;; USU Main Quad Navigation: Finding a path from Old Main to Animal Sciences
;;; Author: Vladimir Kulyukin
(define (problem usu_quad_prob01)
	(:domain usu-main-quad)
  	(:objects OldMain AnimalSciences RayBWest AgriculturalSciences
		  MiddleOfQuad East North South West Agent01)
   	(:init 
	   (building OldMain) 
	   (building AnimalSciences) 
	   (building RayBWest) 
	   (building AgriculturalSciences)
	   (place MiddleOfQuad)
	   (direction East) 
	   (direction North) 
	   (direction South) 
	   (direction West)
	   (agent Agent01)
	   (at Agent01 OldMain)
	   (facing Agent01 East)
	   (path OldMain MiddleOfQuad East)
	   (path MiddleOfQuad OldMain West)
	   (path MiddleOfQuad AnimalSciences North)
	   (path AnimalSciences MiddleOfQuad South)
	   (path RayBWest MiddleOfQuad North)
	   (path MiddleOfQuad RayBWest South)
	   (path MiddleOfQuad AnimalSciences East)
	   (path AnimalSciences MiddleOfQuad West))
	(:goal (and (at Agent01 AnimalSciences)
	            (facing Agent01 North)
		    )))
